# Enable base.yml to be executed as a dispatch workflow with:
#
# gh workflow run base-wrapper.yml \
#  -f quarkus-version=gsmet/quarkus:2.2.4-backports-1 \
#  -f builder-image="quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21"
name: Mandrel-Quarkus tests wrapper

on:
  workflow_dispatch:
    inputs:
      quarkus-version:
        type: string
        description: 'Quarkus version to test `<repo>:<version>`. The `<version>` can be a branch, tag, commit, or "latest".'
        # "latest" is replaced by the latest release available in maven
        default: "quarkusio/quarkus:999-SNAPSHOT"
      graalvm-version:
        type: string
        description: 'Mandrel version to test `<repo>:<version>` (branch, tag, or commit)'
        default: "graalvm/mandrel:graal/master"
      mandrel-packaging-version:
        type: string
        description: 'Mandrel packaging version to test `<repo>:<version>` (branch, tag, or commit)'
        default: "graalvm/mandrel-packaging:master"
      build-type:
        type: choice
        description: 'Build distribution (graal/mandrel) from source or use released binaries, and control if maven should deploy locally'
        default: "mandrel-source-nolocalmvn"
        options:
          - "mandrel-source"
          - "graal-source"
          - "mandrel-source-nolocalmvn"
          - "graal-source-nolocalmvn"
          - "mandrel-release"
          - "graal-release"
      jdk:
        type: choice
        description: 'OpenJDK to use. One of <feature-version>/ga, <feature-version>/ea, e.g. 17/ga or 17/ea (/ga and /ea suffixes are only relevant when building from source)'
        default: "21/ga"
        options:
          - "21/ga"
          - "21/ea"
          - "25/ga"
          - "25/ea"
          - "26/ga"
          - "26/ea"
          - "latest/labsjdk"
      builder-image:
        type: string
        description: 'The builder image to use instead of a release or building from source (e.g. quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21)'
        default: "null"
      build-stats-tag:
        type: string
        description: 'The tag to use for build stats uploads of native tests (e.g. 22.3.0-dev-jdk17-prepatch-x)'
        default: "null"
      gh-runner:
        type: choice
        description: 'The github runner we are building for'
        default: "ubuntu-latest"
        options:
          - "ubuntu-latest"
          - "ubuntu-24.04"
          - "ubuntu-24.04-arm"
      quarkus-additional-build-args:
        type: string
        description: 'Additional arguments to append to the quarkus native build command'
        default: ''
      excluded-native-test-modules:
        type: string
        description: 'Comma separated list of Quarkus modules to exclude from native tests'
        default: ''

jobs:
  process-inputs:
    name: Process inputs
    runs-on: ubuntu-slim
    outputs:
      quarkus-version: ${{ steps.process.outputs.quarkus-version }}
      quarkus-repo: ${{ steps.process.outputs.quarkus-repo }}
      mandrel-version: ${{ steps.process.outputs.mandrel-version }}
      mandrel-repo: ${{ steps.process.outputs.mandrel-repo }}
      mandrel-packaging-version: ${{ steps.process.outputs.mandrel-packaging-version }}
      mandrel-packaging-repo: ${{ steps.process.outputs.mandrel-packaging-repo }}
      build-type: ${{ steps.process.outputs.build-type }}
      jdk: ${{ steps.process.outputs.jdk }}
      builder-image: ${{ steps.process.outputs.builder-image }}
      build-stats-tag: ${{ steps.process.outputs.build-stats-tag }}
    steps:
      - id: process
        run: |
          QUARKUS_INPUT="${{ github.event.inputs.quarkus-version }}"
          echo "quarkus-repo=$(echo $QUARKUS_INPUT | cut -d ':' -f 1)" >> $GITHUB_OUTPUT
          echo "quarkus-version=$(echo $QUARKUS_INPUT | cut -d ':' -f 2)" >> $GITHUB_OUTPUT
          echo "mandrel-repo=$(echo ${{ github.event.inputs.graalvm-version }} | cut -d ':' -f 1)" >> $GITHUB_OUTPUT
          echo "mandrel-version=$(echo ${{ github.event.inputs.graalvm-version }} | cut -d ':' -f 2)" >> $GITHUB_OUTPUT
          echo "mandrel-packaging-repo=$(echo ${{ github.event.inputs.mandrel-packaging-version }} | cut -d ':' -f 1)" >> $GITHUB_OUTPUT
          echo "mandrel-packaging-version=$(echo ${{ github.event.inputs.mandrel-packaging-version }} | cut -d ':' -f 2)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
  delegate:
    needs: process-inputs
    uses: ./.github/workflows/base.yml
    with:
      quarkus-version: ${{ needs.process-inputs.outputs.quarkus-version }}
      quarkus-repo: ${{ needs.process-inputs.outputs.quarkus-repo }}
      mandrel-version: ${{ needs.process-inputs.outputs.mandrel-version }}
      mandrel-repo: ${{ needs.process-inputs.outputs.mandrel-repo }}
      mandrel-packaging-version: ${{ needs.process-inputs.outputs.mandrel-packaging-version }}
      mandrel-packaging-repo: ${{ needs.process-inputs.outputs.mandrel-packaging-repo }}
      build-type: ${{ github.event.inputs.build-type }}
      jdk: ${{ github.event.inputs.jdk }}
      builder-image: ${{ github.event.inputs.builder-image }}
      build-stats-tag: ${{ github.event.inputs.build-stats-tag }}
      gh-runner: ${{ github.event.inputs.gh-runner }}
      quarkus-additional-build-args-append: ${{ github.event.inputs.quarkus-additional-build-args }}
      excluded-native-test-modules: ${{ github.event.inputs.excluded-native-test-modules }}
    secrets:
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
