name: Bi-weekly CI

on:
  push:
    paths:
      - '.github/workflows/biweekly.yml'
      - '.github/workflows/base.yml'
      - '.github/workflows/base-windows.yml'
      - '.github/workflows/compute-build-config.yml'
      - '.github/workflows/resolve-quarkus-version.yml'
      - '.github/workflows/build-quarkus.yml'
  pull_request:
    paths:
      - '.github/workflows/biweekly.yml'
      - '.github/workflows/base.yml'
      - '.github/workflows/base-windows.yml'
      - '.github/workflows/compute-build-config.yml'
      - '.github/workflows/resolve-quarkus-version.yml'
      - '.github/workflows/build-quarkus.yml'
  schedule:
    # Run every two weeks at 00:00
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

# The following aims to reduce CI CPU cycles by:
# 1. Cancelling any previous builds of this PR when pushing new changes to it
# 2. Cancelling any previous builds of a branch when pushing new changes to it in a fork
# 3. Cancelling any pending builds, but not active ones, when pushing to a branch in the main
#    repository. This prevents us from constantly cancelling CI runs, while being able to skip
#    intermediate builds. E.g., if we perform two pushes the first one will start a CI job and
#    the second one will add another one to the queue; if we perform a third push while the
#    first CI job is still running the previously queued CI job (for the second push) will be
#    cancelled and a new CI job will be queued for the latest (third) push.
concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'graalvm/mandrel' }}

jobs:
  ####
  # Test Quarkus main with latest Mandrel sources and maven-deploy-local
  # This ensures Quarkus can still build with the latest GraalVM/Mandrel SDK
  ####
  q-main-mandrel-25_0-with-local-maven-and-assertions:
    name: "Q main M 25.0 with local maven and assertions"
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    uses: ./.github/workflows/base.yml
    with:
      quarkus-version: "main"
      mandrel-version: "mandrel/25.0"
      build-type: "mandrel-source"
      jdk: "25/ea"
      issue-number: "929"
      issue-repo: "graalvm/mandrel"
      mandrel-packaging-version: "25.0"
      quarkus-additional-build-args-append: "-ea,-esa,-J-ea,-J-esa"
      excluded-native-test-modules: "maven"
    secrets:
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
  ####
  # Test Quarkus main with latest GraalVM sources and maven-deploy-local
  # This ensures Quarkus can still build with the latest GraalVM SDK
  ####
  q-main-graal-master-with-local-maven-and-assertions:
    name: "Q main G master with local maven and assertions"
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    uses: ./.github/workflows/base.yml
    with:
      quarkus-version: "main"
      mandrel-version: "graal/master"
      build-type: "graal-source"
      jdk: "latest/ea"
      issue-number: "978"
      issue-repo: "graalvm/mandrel"
      quarkus-additional-build-args-append: "-ea,-esa,-J-ea,-J-esa"
      excluded-native-test-modules: "maven"
    secrets:
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}

# Made with Bob
